### ISSUE TITLE
FR: für Contao 3.5 und MM 2.0.0 fit machen

### ISSUE THREAD

**Issue by zonky2** [MetaModels/demo-installer#1]
siehe auch https://github.com/MetaModels/demo-movie-database/issues/1

**Comment by cliffparnitzky** [comment]
Ich werde mich der Sache mal annehmen.

**Comment by zonky2** [comment]
sounds good!

**Comment by zonky2** [comment]
die Movie-Demo läuft auf aktuellem MM und Contao - https://now.metamodel.me/de/aktuelles/details/2017-august-infos

eine Installation per "Installer" wird nicht mehr unterstützt
